require:
  - rubocop/cop/internal_affairs
  - rubocop-minitest
  - rubocop-rake

AllCops:
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - '.git/**/*'
    - '.bundle/**/*'
    - 'bin/*'

Style/RedundantReturn:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'test/**/test_*.rb'
    - '*.gemspec'
