require:
  - rubocop/cop/internal_affairs
  - rubocop-minitest
  - rubocop-rake

AllCops:
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - '.git/**/*'
    - '.bundle/**/*'
    - 'bin/*'
  TargetRubyVersion: 2.6.1

Style/RedundantReturn:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'test/**/test_*.rb'
    - '*.gemspec'
Style/YodaCondition:
  EnforcedStyle: require_for_all_comparison_operators
