name: CI
on:
  pull_request:

jobs:
  minitest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
          bundler-cache: false

      - name: Install Gems
        run: bin/bundle

      - name: Run Minitest
        run: bin/rake test
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
          bundler-cache: false

      - name: Install Gems
        run: bin/bundle

      - name: Run Rubocop
        run: bin/rubocop
